# Generated by Django 4.2.3 on 2023-09-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_alter_recipymodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipymodel',
            name='user',
        ),
    ]
