# Generated by Django 4.2.3 on 2023-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0005_alter_recipymodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipymodel',
            name='category',
            field=models.CharField(choices=[('Dessert', 'Dessert'), ('Main Course', 'Main Course'), ('Appetizer', 'Appetizer')], max_length=50),
        ),
    ]
